export const INITIAL_WEATHER_DATA_REQUESTED = 'INITIAL_WEATHER_DATA_REQUESTED';
export const INITIAL_WEATHER_DATA_SUCCEEDED = 'INITIAL_WEATHER_DATA_SUCCEEDED';
export const WEATHER_DATA_REQUESTED = 'WEATHER_DATA_REQUESTED';